### ISSUE TITLE
[H-1] Fluxo de telas

### ISSUE THREAD

**Issue by nathaliacm** [nathaliacm/Haub#3]
- [x] Criar link da tela inicial para o Drawer
  - [x] Criar tela do Drawer na tela inicial
    - [x] Criar um logo para apresentação no Drawer
    - [x] Criar link para a tela de perfil
    - [x] Criar link para logout 
    - [x] Customizar elementos/widgets
      - [x] Criar uma customização para o listTile
      - [x] Widget Container
      - [x] Elemento RaisedButtom

**Comment by ceciliasoa** [comment]
Concluído em pair programming com o Thiago.
