### ISSUE TITLE
[H-2] Customizar tela de mensagens(tela principal)

### ISSUE THREAD

**Issue by nathaliacm** [nathaliacm/Haub#4]
- [x] Criar Tab bar
   - [x] Adicionar bottom ao appBar
   - [x] Criar página para cada tabBar
   - [x] Configurar interface
- [x] Criar tabel customizada (conversas)
   - [x] Criar model com nome, ultima mensagem e hora
   - [x] Criar listView para receber model de conversa
   - [x] Adicionar o fluxo para o chat ao listView
- [x] Adicionar bottom navigation (adicionar)
   - [x] Criar floatingActionButton no centro da tela
   - [x] Criar o bottomAppBar
   - [x] Adicionar borda entre o bottomAppBar e o botão flutuante 
   - [x] Configurar tamanho e cor

**Comment by ceciliasoa** [comment]
Tela concluída
