### ISSUE TITLE
[H-4] Implementar Chat

### ISSUE THREAD

**Issue by nathaliacm** [nathaliacm/Haub#6]
- [x] popmenubuttom na app bar
- [x] Interface de mensagens
   - [x] Balões nas mensagens
   - [x] Ordem, pela data, das mensagens
- [x] Implementar barra de envio
   - [x] TextField
   - [x] Botão de enviar 
      - [x] Imagem circular atrás do botão
      - [x] Habilitar/desabilitar botão (send) ao digitar mensagens

**Comment by Robsonmxms** [comment]
Tela implementada com sucesso
